FROM golang:1.22-alpine as builder
WORKDIR /app
COPY . .
RUN go mod tidy
RUN go build -o task-service ./task-management/cmd/task-service/main.go

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/task-service .
EXPOSE 8080
CMD ["./task-service"]
